django_CRM_Project/urls.py
from django.contrib import admin
from django.urls import path,include
# load static file
from django.conf import settings
from django.conf.urls.static import static
from .views import home_page,header,footer
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from organization.views import OrganizationViewSetAPI

router = DefaultRouter()
router.register('organization', OrganizationViewSetAPI)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page,name="homepage"),
    path('header', header, name="header"),
    path('footer', footer, name="footer"),
    path('', include('user_accounts.urls')),
    path('', include('product.urls')),
    path('', include('organization.urls')),
    path('', include('quote.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),

]



# Static File Setting
if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # python manage.py collectstatic

    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organization/urls.py
from django.urls import path
from .views import Organization_Form,Organization_List,Organization_Detail, Organization_update

app_name = 'organization'
urlpatterns = [
    path('formorg',Organization_Form.as_view(),name='form'),
    path('listorg',Organization_List.as_view(),name='list'),
    path('detailorg/<int:pk>',Organization_Detail.as_view(),name='detail'),
    path('updateorg/<int:pk>',Organization_update.as_view(),name="Update"),
    ]

quote/urls.py
from django.urls import path
from .views import Quotes_Form, ListQuotes, DownloadQuote, send_quote_email, Follow_Up, ListFollow_Up

app_name = 'quote'
urlpatterns = [
    path('formquote', Quotes_Form.as_view(), name='form_quote'),
    path('listquote', ListQuotes.as_view(), name='list_quote'),
    path('download/<int:pk>/', DownloadQuote.as_view(), name='pdf_quote'),
    path('email/<int:pk>', send_quote_email, name='email_quote'),
    path('followup/<int:pk>/', Follow_Up.as_view(), name='follow_up'),
    path('listfollowup', ListFollow_Up.as_view(), name='list_follow_up'),

]

organization/models.py
from django.db import models
from django.contrib.auth import get_user_model
from product.models import Product
from django.core.validators import RegexValidator

# <--------------------| رجکس |-------------------->

email_regex = RegexValidator(regex='/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{1,3})$/', message='ایمیل شما معتبر نیست')
mobile_regex = RegexValidator(regex='((\+98|0)?9\d{9})', message='موبایل شما معتبر نمی باشد')
phone_regex = RegexValidator(regex='^((?:\+98|0)(\d){2}(\d){8})$', message='تلفن شما معتبر نمی باشد')


# <--------------------| مدل محصول سازمان |-------------------->

class OrganizationProduct(models.Model):
    name = models.CharField(max_length=50, verbose_name='محصولات تولیدی کارفرما')

    class Meta:
        verbose_name = 'محصول تولیدی'
        verbose_name_plural = 'محصولات تولیدی'

    def __str__(self):
        return self.name

    def get_suggest_product(self):
        return [product for product in self.product_set.all()]


# <--------------------| استان |-------------------->

class Province(models.Model):
    name = models.CharField(max_length=100, verbose_name="استان", unique=True)

    class Meta():
        verbose_name = "استان"
        verbose_name_plural = "استان ها"

    def __str__(self):
        return self.name



class Organization(models.Model):
    province_name = models.CharField(max_length=20, verbose_name='استان')
    organization_name = models.CharField(max_length=50, verbose_name='نام سازمان')
    organization_phone = models.CharField(max_length=11, verbose_name='شماره تلفن سازمان', unique=True)
    organization_staff = models.PositiveIntegerField(verbose_name='تعداد کارگران')
    organization_product = models.ManyToManyField(OrganizationProduct, verbose_name='محصولات تولیدی')
    personnel_name = models.CharField(max_length=50, verbose_name="نام و نام خانوادگی کارفرما")
    personnel_mobile = models.CharField(max_length=11, verbose_name='موبایل کارفرما')
    personnel_email = models.EmailField(verbose_name='ایمیل کارفرما', blank=True)
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    creator = models.ForeignKey(get_user_model(), verbose_name='کاربر ثبت کننده', on_delete=models.CASCADE)

    class Meta:
        unique_together = ['organization_name', 'creator']
        verbose_name = 'سازمان'
        verbose_name_plural = 'سازمانها'

    def __str__(self):
        return self.organization_name

    def get_organization_product(self):
        return [product.name for product in self.organization_product.all()]

    def get_suggest_product(self):
        p = list()
        for product in self.organization_product.all():
            for l in product.get_suggest_product():
                p.append(l.name)
        p = set(p)
        return list(p)

organization/forms.py
from django import forms
from organization import models


# <--------------------| فرم سازمان |-------------------->

class OrganizationForm(forms.ModelForm):
    class Meta:
        model = models.Organization
        fields = ['province_name', 'organization_name', 'organization_phone', 'organization_staff',
                  'organization_product', 'personnel_name', 'personnel_mobile', 'personnel_email']


# <--------------------| فرم محصول سازمان |-------------------->

class OrganizationProductForm(forms.ModelForm):
    class Meta:
        model = models.OrganizationProduct
        fields = ['name']

organization/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from . import models, forms, serializers
from rest_framework.permissions import IsAuthenticated
from rest_framework.viewsets import ModelViewSet
from rest_framework_simplejwt.authentication import JWTAuthentication
from quote.models import FollowUp

# <--------------------| فرم ایجاد سازمان |-------------------->

class Organization_Form(CreateView):
    model = models.Organization
    form_class = forms.OrganizationForm
    template_name = 'organization/form_organization.html'
    success_url = reverse_lazy('organization:list')

    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.info(self.request, form.errors)
        return super().form_invalid(form)


# <--------------------| لیست سازمان |-------------------->

class Organization_List(ListView):
    model = models.Organization
    template_name = "organization/list_organization.html"
    paginate_by = 6

    # def get_queryset(self):
    #     qs = super().get_queryset()
    #     if not self.request.user.is_superuser:
    #         qs = qs.filter(creator=self.request.user)
    #     return qs


# <--------------------| جزپیات سازمان |-------------------->

class Organization_Detail(DetailView):
    model = models.Organization
    template_name = 'organization/detail_organization.html'

    # def get_queryset(self):
    #     organization = models.Organization.objects.filter(pk=self.kwargs['pk'], creator=self.request.user)
    #     return organization

    def get_context_data(self, **kwargs):
        follow_up = FollowUp.objects.filter(organization_id=self.kwargs['pk'],)
        organization = models.Organization.objects.get(pk=self.kwargs['pk'], creator=self.request.user)
        context = {'follow_up':follow_up, 'organization': organization}
        return context

# <--------------------| ویرایش سازمان |-------------------->

class Organization_update(UpdateView):
    model = models.Organization
    template_name = 'organization/update_organization.html'
    form_class = forms.OrganizationForm

    def get_queryset(self):
        organization = models.Organization.objects.filter(pk=self.kwargs['pk'], creator=self.request.user)
        return organization

    def get_success_url(self):
        return redirect('organization:detail', kwargs={'pk': self.object.pk})

# <--------------------| API |-------------------->
class OrganizationViewSetAPI(ModelViewSet):
    serializer_class = serializers.OrganizationSerializer
    permission_classes = [IsAuthenticated]
    authentication_classes = [JWTAuthentication]
    queryset = models.Organization.objects.all()

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(creator=self.request.user)

    def perform_create(self, serializer):
        serializer.save(creator=self.request.user)

templates/organization/detail_organization.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}

{% block content %}


        <div class="container">
        <section id="form"><!--form-->
            <div class="row">
                                <div class="col-sm-4 col-sm-offset-1">
                                        <div class="text-center">
                        <h2>{{ organization.organization_name }}</h2>
                    </div>
                    <div>
                        <a href="{% url 'organization:list' %}" class="btn btn-info">بازگشت</a>
                        <a href="{% url 'quote:form_quote' %}" class="btn btn-info">پیش فاکتور</a>
                        <a href="{% url 'organization:Update' organization.pk %}" class="btn btn-info">ویرایش</a>
                    </div>
                    <div class="card-body">
                        استان : {{ organization.province_name }}
                        <br>
                        تلفن : {{ organization.organization_phone }}
                        <br>
                        تاریخ ثبت : {{ organization.timestamp.date }}
                        <br>
                        تعداد کارگر : {{ organization.organization_staff }}
                        <br>
                        ثبت توسط : {{ organization.creator }}
                        <br>
                        محصولات تولیدی : {% for product in organization.get_organization_product %} ,{{ product }}{% endfor %}
                        <br>
                        محصولات پیشنهادی : {% for product in organization.get_suggest_product %} ,{{ product }} {% endfor %}
                    </div>
                    <div class="text-center">
                        <h4>اطلاعات مخاطب</h4>
                    </div>
                    <div class="card-body">
                        نام مخاطب : {{ organization.personnel_name }}
                        <br>
                        تلفن مخاطب : {{ organization.personnel_mobile }}
                        <br>
                    </div>
                    <div class="text-center">
                        <h2>تاریخچه پیگیری</h2>
                    </div>
                    <div class='text-white mt-lg-5' style="margin-left: 15%; margin-right: 15%;">
                        <table class='table table-dark'>
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>کاربر</th>
                                <th>تاریخ</th>
                                <th>گزارش</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for followup in follow_up %}
                                <tr>
                                    <th>{{ forloop.counter }}</th>
                                    <th>
                                        {{ followup.creator }}
                                    </th>
                                    <th>{{ followup.timestamp.date }}</th>
                                    <th>
                                        {{ followup.text }}
                                    </th>
                                    <th>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <!--/form-->


                        <div class="clearfix"></div>
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                            {% endif %}
                            {% for page in paginator.page_range %}
                                {% if page == page_obj.number %}
                                    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="?page={{ page }}">{{ page }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                            {% endif %}
                        </ul>
{% endblock %}

templates/organization/form_organization.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <section id="form"><!--form-->
            <div class="row">
                <div class="col-sm-4 col-sm-offset-1">
                    <div class="signup-form"><!--sign up form-->
                        <h2>تعریف سازمان</h2>
                        <form method="post">
                            {% csrf_token %}

                            <label for="province_name">نام استان</label>
                            <input type="text" id="province_name" name="province_name" placeholder="نام استان">
                            <label for="organization_name">نام سازمان</label>
                            <input type="text" id="organization_name" name="organization_name" placeholder="نام سازمان">
                            <label for="organization_phone">شماره تلفن سازمان</label>
                            <input type="text" id="organization_phone" name="organization_phone"
                                   placeholder="شماره تلفن سازمان" maxlength="11">
                            <label for="organization_staff">تعداد کارگران</label>
                            <input type="text" id="organization_staff" name="organization_staff"
                                   placeholder="تعداد کارگران">
                            <label for="organization_product" class="form-label">محصولات تولیدی</label>
                            <select id='organization_product' name='organization_product' style="text-align: right;"
                                    class="form-select" multiple>
                                {% for item in form.fields.organization_product.queryset %}
                                    {% if item %}
                                        <option value="{{ item.pk }}">{{ item }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                            <label for="personnel_name">کاربر ثبت کننده</label>
                            <input type="text" id="personnel_name" name="personnel_name" placeholder="کاربر ثبت کننده">
                            <label for="personnel_mobile">شماره همراه کاربر</label>
                            <input type="text" id="personnel_mobile" name="personnel_mobile"
                                   placeholder="شماره همراه کاربر" maxlength="11">
                            <label for="personnel_email">ایمیل سازمان</label>
                            <input type="text" id="personnel_email" name="personnel_email" placeholder="ایمیل سازمان">
                            <button type="submit" class="btn btn-default">ثبت نام</button>

                        </form>
                    </div><!--/sign up form-->
                </div>
            </div>
        </section>
    </div>
    <!--/form-->


{% endblock %}

templates/organization/list_organization.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}
{% load i18n %}


{% block content %}
    <section>
        <div class="container">
            <div class="row">

                <div class="col-sm-9 padding-right">
                    <div class="features_items"><!--features_items-->
                        <h2 class="title text-center">لیست کارفرمایان</h2>
                                <div class='text-white' dir='rtl' style='margin-top: 100px;'>
                                    <table class="table table-dark">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>{% trans "نام سازمان" %}</th>
                                                <th>{% trans "کارفرما" %}</th>
                                                <th>{% trans "ثبت کننده" %}</th>
                                                <th>{% trans "عملیات" %}</th>
                                            </tr>
                                        <thead>
                                        <tbody>
                                            {% for item in object_list %}
                                                <tr>
                                                    <td>{{forloop.counter}}</td>
                                                    <td>
                                                        <a style='text-decoration: none; color: red;' href="{% url 'organization:detail' item.pk %}">{{item.organization_name}}</a>
{#                                                        <a style='text-decoration: none; color: red;' href="#">{{item.organization_name}}</a>#}
                                                    </td>
                                                    <td>{{item.personnel_name}}</td>
                                                    <td>{{item.creator}}</td>
                                                    <td>
                                                        <a href="{% url 'quote:follow_up' item.pk %}" style='text-decoration: none; color: red;'>{% trans "عملیات پیگیری" %}</a>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>


                        <div class="clearfix"></div>
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                            {% endif %}
                            {% for page in paginator.page_range %}
                                {% if page == page_obj.number %}
                                    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="?page={{ page }}">{{ page }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                            {% endif %}
                        </ul>
                    </div><!--features_items-->
                </div>

            </div>
        </div>
    </section>
{% endblock %}

templates/organization/update_organization.html
{% extends 'shared/_MainLayout.html' %}
{% load widget_tweaks %}


{% block content %}

        <div class="container">
        <section id="form"><!--form-->
            <div class="row">
                <div class="col-sm-4 col-sm-offset-1">
                    <div class="text-center">
                        <h2>ویرایش {{ form.name.value }}</h2>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="province_name">استان</label>
                            {% render_field form.province_name class+="form-control" type="select" %}
                        </div>
                        <div class="form-group">
                            <label for="organization_name">نام سازمان</label>
                            {% render_field form.organization_name class+="form-control" type="text" %}
                        </div>
                        <div class="form-group">
                            <label for="organization_phone">تلفن</label>
                            {% render_field form.organization_phone class+="form-control" type="text" %}
                        </div>
                        <div class="form-group">
                            <label for="organization_staff">تعداد کارگران</label>
                            {% render_field form.organization_staff class+="form-control" type="number" min="0" %}
                        </div>
                        <div class="form-group">
                            <label for="organization_product" class="form-label">محصولات تولیدی</label>
                            {% render_field form.organization_product class+="form-control" type="select" %}
                        </div>
                        <div class="form-group">
                            <label for="personnel_name">نام و نام خانوادگی مخاطب</label>
                            {% render_field form.personnel_name class+="form-control" type="text" %}
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="personnel_mobile">تلفن مخاطب</label>
                                {% render_field form.personnel_mobile class+="form-control" type="text" %}
                            </div>
                            <div class="form-group col-md-6">
                                <label for="personnel_email">ایمیل مخاطب</label>
                                {% render_field form.personnel_email class+="form-control" type="email" %}
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary">ذخیره</button>
                    </form>                </div>
                            </div>
        </section>
    </div>



{% endblock %}