django_CRM_Project/urls.py
from django.contrib import admin
from django.urls import path,include
# load static file
from django.conf import settings
from django.conf.urls.static import static
from .views import home_page,header,footer
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from organization.views import OrganizationViewSetAPI

router = DefaultRouter()
router.register('organization', OrganizationViewSetAPI)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page,name="homepage"),
    path('header', header, name="header"),
    path('footer', footer, name="footer"),
    path('', include('user_accounts.urls')),
    path('', include('product.urls')),
    path('', include('organization.urls')),
    path('', include('quote.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),

]



# Static File Setting
if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # python manage.py collectstatic

    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quote/urls.py
from django.urls import path
from .views import Quotes_Form, ListQuotes, DownloadQuote, send_quote_email, Follow_Up, ListFollow_Up

app_name = 'quote'
urlpatterns = [
    path('formquote', Quotes_Form.as_view(), name='form_quote'),
    path('listquote', ListQuotes.as_view(), name='list_quote'),
    path('download/<int:pk>/', DownloadQuote.as_view(), name='pdf_quote'),
    path('email/<int:pk>', send_quote_email, name='email_quote'),
    path('followup/<int:pk>/', Follow_Up.as_view(), name='follow_up'),
    path('listfollowup', ListFollow_Up.as_view(), name='list_follow_up'),

]

quote/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Sum, F, Case, When
from django.core.validators import MinValueValidator, MaxValueValidator


# <--------------------| مدل پیش فاکتور |-------------------->

class Quote(models.Model):
    organization = models.ForeignKey("organization.Organization", on_delete=models.PROTECT, verbose_name="سازمان")
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    creator = models.ForeignKey(get_user_model(), verbose_name='کاربر ثبت کننده', on_delete=models.CASCADE)
    tax = 9

    class Meta:
        verbose_name = 'پیش فاکتور'
        verbose_name_plural = 'پیش فاکتورها'

    def __str__(self):
        return f'{self.organization}'

    def get_total_number(self):  # جمع تعداد
        return self.quoteitem_set.all(). \
            aggregate(Sum('number')).get('number__sum', 0)

    def get_total_base_price(self):  # جمع قیمت پایه
        return self.quoteitem_set.all().annotate(total_base_price=F('number') * F('price')) \
            .aggregate(Sum('total_base_price'))['total_base_price__sum']

    def get_quote_discount(self):  # جمع تخفیف ها
        return self.quoteitem_set.all().annotate(
            total_base_price=F('number') * F('price')).annotate(
            total_discount=(F('discount') * F('total_base_price') / 100)) \
            .aggregate(Sum('total_discount'))['total_discount__sum']

    def get_quote_tax(self, tax=tax):  # جمع مالیات
        return self.quoteitem_set.all().annotate(
            total_base_price=F('number') * F('price')).annotate(
            total_price=F('total_base_price') - (F('discount') * F('total_base_price') / 100)).annotate(
            total_tax=Case(
                When(product__tax=True, then=(F('total_price') * tax / 100)),
                When(product__tax=False, then=0),
                output_field=models.PositiveIntegerField()
            )
        ).aggregate(Sum('total_tax'))['total_tax__sum']

    def get_total_price(self, tax=tax):  # جمع کلی
        return self.quoteitem_set.all().annotate(
            total_base_price=F('number') * F('price')).annotate(
            total_price=F('total_base_price') - (F('discount') * F('total_base_price') / 100)).annotate(
            total_price=Case(
                When(product__tax=True, then=F('total_price') + (F('total_price') * tax / 100)),
                When(product__tax=False, then=F('total_price')),
                output_field=models.PositiveIntegerField()
            )
        ).aggregate(Sum('total_price'))['total_price__sum']


# <--------------------| آیتم پیش فاکتور |-------------------->

class QuoteItem(models.Model):
    quote = models.ForeignKey("Quote", on_delete=models.CASCADE, verbose_name='پیش فاکتور')
    product = models.ForeignKey('product.Product', on_delete=models.CASCADE, verbose_name="محصول")
    price = models.PositiveIntegerField(default=0, verbose_name='قیمت')
    number = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)], verbose_name='تعداد')
    discount = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(100)], verbose_name='درصد تخفیف')

    class Meta:
        verbose_name = 'رکورد پیش فاکتور'
        verbose_name_plural = 'رکورد پیش فاکتورها'

    def __str__(self):
        return f'{self.quote} {self.product}'

    def get_total_price(self):
        return self.number * self.price


# <--------------------| تاریخچه ارسال ایمیل |-------------------->

class QuoteEmailHistory(models.Model):
    receiver = models.EmailField(verbose_name="ایمیل گیرنده")
    sent_email = models.BooleanField(default=False, verbose_name="ایمیل ارسال شد؟")
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    user_sender = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, verbose_name="کاربر ارسال کننده")

    def __str__(self):
        return self.receiver


# <--------------------| پیگیری |-------------------->

class FollowUp(models.Model):
    organization = models.ForeignKey('organization.Organization', verbose_name="سازمان", on_delete=models.CASCADE)
    creator = models.ForeignKey(get_user_model(), verbose_name='کاربر ثبت کننده', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    text = models.TextField(verbose_name='متن پیگیری', default=None)

    class Meta:
        verbose_name = 'پیگیری'
        verbose_name_plural = 'پیگیری ها'

quote/forms.py
from django import forms
from . import models
from django.forms import modelformset_factory

# <--------------------| فرم پیش فاکتور |-------------------->

QuoteItemCreateFormSet = modelformset_factory(models.QuoteItem, fields=('product', 'price', 'number', 'discount'),
                                              extra=1)


# <--------------------| فرم پیگیری |-------------------->

class FollowUpForm(forms.ModelForm):
    class Meta:
        model = models.FollowUp
        fields = ['text']

quote/views.py
# import weasyprint as weasyprint
from django.core import mail
from django.http import JsonResponse
from django.shortcuts import redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView, DetailView, CreateView
from quote.models import QuoteItem, Quote, FollowUp
from . import forms
from django.contrib import messages
from organization.models import Organization


# <--------------------| فرم پیش فاکتور |-------------------->

class Quotes_Form(CreateView):
    template_name = 'quote/form_quote.html'

    def get_context_data(self, **kwargs):
        formset = forms.QuoteItemCreateFormSet(queryset=QuoteItem.objects.none())
        organizations = Organization.objects.filter(creator=self.request.user)
        return {'formset': formset, 'organizations': organizations}

    def post(self, *args, **kwargs):
        formset = forms.QuoteItemCreateFormSet(data=self.request.POST)
        if formset.is_valid():
            organization = get_object_or_404(Organization, pk=self.request.POST['organization'],
                                             creator=self.request.user)
            quote = Quote.objects.create(creator=self.request.user, organization=organization)
            for form in formset:
                form.instance.quote = quote
                form.save()
            messages.success(self.request, "ثبت شد")
            return redirect("quote:list_quote")


# <--------------------| لیست پیش فاکتور |-------------------->

class ListQuotes(ListView):
    template_name = 'quote/list_quote.html'
    model = Quote
    paginate_by = 4


# <--------------------| دانلود پیش فاکتور |-------------------->

class DownloadQuote(DetailView):
    template_name = 'quote/pdf_quote.html'
    model = Quote

    # def get(self, request, *args, **kwargs):
    # response = super().get(request, *args, **kwargs)
    # content = response.rendered_content
    # pdf = weasyprint.HTML(string=content, base_url='http://127.0.0.1:8000').write_pdf()
    # pdf_response = HttpResponse(content=pdf, content_type='application/pdf')
    # return pdf_response


# <--------------------| ارسال ایمیل |-------------------->

@require_http_methods(["GET"])
def send_quote_email(request, pk):
    quote = get_object_or_404(Quote, pk=pk, creator=request.user)
    text = render_to_string('quotetext.txt', {'object': quote})
    email = quote.organization.personnel_email
    sender = request.user.email
    emails = (
        ('Hello', text, sender, [email, ]),
    )
    results = mail.send_mass_mail(emails)
    print(results)
    messages.success(request, 'ایمیل با موفقیت ارسال شد.')
    return reverse_lazy('quote:list_quote')


# <--------------------| پیگیری فروش |-------------------->

class Follow_Up(CreateView):
    template_name = 'quote/follow_up.html'
    model = FollowUp
    form_class = forms.FollowUpForm

    def get_context_data(self, **kwargs):
        context = {
            'organization': Organization.objects.get(pk=self.kwargs['pk']),
        }
        return context

    def form_invalid(self, form):
        return JsonResponse(data={
            'success': 'False',
        }, status=400)

    def form_valid(self, form):
        form.save(commit=False).creator = self.request.user
        form.save(commit=False).organization = Organization.objects.get(pk=self.kwargs['pk'])
        form.save()
        return JsonResponse(data={
            'success': 'True',
        }, status=200)


# <--------------------| لیست پیگیری |-------------------->

class ListFollow_Up(ListView):
    template_name = 'quote/list_follow_up.html'
    model = FollowUp
    paginate_by = 3

    def get_queryset(self):
        qs = super().get_queryset()
        pk = self.kwargs.get('pk', None)
        qs = qs.filter(organization__pk=pk)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        organization_obj = get_object_or_404(
            klass='organization.Organization',
            pk=self.kwargs.get('pk', None))

        context['organization'] = organization_obj

        return context

templates/quote/follow_up.html
{% extends 'shared/_MainLayout.html' %}
{% load widget_tweaks %}
{% load i18n %}


{% block content %}
    <div class="text-center">
        <h2>ثبت پیگیری</h2>
    </div>
    <form method="post" id="formsubmit">
        {% csrf_token %}
        <div class="form-group">
            <label for="text"></label>
            <textarea id="text" name="text" rows="5"
                      placeholder="{{ form.text.label }}"></textarea>
        </div>

        <button type="submit" class="btn btn-primary" id="btnsubmit">ذخیره</button>
    </form>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $('#btnsubmit').on('click', function (event) {
                var text = $('#text').val();

                $.ajax({
                    method: 'POST',
                    url: '{% url 'quote:follow_up' organization.pk %}',
                    data: {
                        text: text
                    },
                    success: function (response) {
                        alert('با موفقیت ذخیره شد.');
                    },
                    error: function (response) {
                        alert('اطلاعات وارد شده صحیح نیست.');
                    },

                })
            });
        });
    </script>
{% endblock %}

templates/quote/form_quote.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}


{% block content %}

        <div class="container">
        <section id="form"><!--form-->
            <div class="row">
                <div class="col-sm-4 col-sm-offset-1">
                     <form id="form-container" method="POST">
                    {% csrf_token %}
                    {{ formset.management_form }}
                    <div class="col-md-8 col-12">
                        <div class="form-group">
                            <label for="organization">سازمان</label>
                            <select class="choices form-select"
                                    name="organization" id="organization">
                                <optgroup label="organization">
                                    {% for organization in organizations %}
                                        <option value="{{ organization.id }}">{{ organization }}</option>
                                    {% endfor %}
                                </optgroup>
                            </select>
                        </div>
                    </div>
                    <label for="organization">محصولات</label>
                    <br>
                    {% for form in formset %}
                        <div class="formset">
                            <div class="col-md-11 col-12">
                                <div class="form-group">
                                    <div class="col-md-12 mb-10">
                                        <div class="input-group mb-10">
                                            <label class="input-group-text"
                                                   for="id_form-0-product">محصول</label>
                                            {% render_field form.product class+="form-select" %}
                                            <input type="number" class="form-control" name="form-0-price"
                                                   min="0" id="id_form-0-price"
                                                   placeholder="قیمت" required>
                                            <input type="number" class="form-control" name="form-0-number"
                                                   min="1" id="id_form-0-number"
                                                   placeholder="تعداد" required>
                                            <input type="number" class="form-control" name="form-0-discount"
                                                   min="0" max="100" id="id_form-0-discount"
                                                   placeholder="درصد تخفیف" required>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <button id="add-form" type="button" class="btn btn-secondary me-1 mb-1">محصول جدید</button>
                    <button type="submit" class="btn btn-primary me-1 mb-1">ذخیره</button>
                </form>
                </div>
            </div>
        </section>
    </div>
    <!--/form-->


{% endblock %}

{% block scripts %}
    <script>
        let birdForm = document.querySelectorAll(".formset")
        let container = document.querySelector("#form-container")
        let addButton = document.querySelector("#add-form")
        let totalForms = document.querySelector("#id_form-TOTAL_FORMS")
        let formNum = birdForm.length - 1
        addButton.addEventListener('click', addForm)

        function addForm(e) {
            e.preventDefault()
            let newForm = birdForm[0].cloneNode(true)
            let formRegex = RegExp(`form-(\\d){1}-`, 'g')
            formNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`);
            container.insertBefore(newForm, addButton)
            totalForms.setAttribute('value', `${formNum + 1}`)
        }
    </script>
{% endblock %}

templates/quote/list_follow_up.html
{% extends 'shared/_MainLayout.html' %}
{% load i18n %}

{% block content %}
    <div class='row'>
        <div class='row'>
            <div class='text-dark mt-lg-5 fw-bold fs-5'>
                <h2>{{organization.organization_name}} {% trans "تاریخچه پیگیری شرکت" %}</h2>
            </div>
        </div>

        <div class='row text-white'>
            <table class='table table-dark'>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>{% trans "کاربر" %}</th>
                        <th>{% trans "تاریخ" %}</th>
                        <th>{% trans "سفارش" %}</th>
                    </tr>
                </thead>

                <tbody>
                    {% for item in object_list  %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{item.creator}}</td>
                            <td>{{item.timmpstamp}}</td>
                            <td>{{item.text}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

templates/quote/list_quote.html
{% extends 'shared/_MainLayout.html' %}
{% load i18n %}

{% block content %}
    <div class="text-center">
        <h2>لیست پیش فاکتور ها</h2>
    </div>
    <div class='text-white mt-lg-5' style="margin-left: 15%; margin-right: 15%;">
        <table class='table table-dark'>
            <thead>
            <tr>
                <th>#</th>
                <th>نام مشتری</th>
                <th>دستگاه ها</th>
                <th>فایل خروجی</th>
                <th>ارسال ایمیل به مخاطب</th>
            </tr>
            </thead>

            <tbody>
                {% for quote in object_list %}
                    <tr>
                        <th>{{forloop.counter}}</th>
                        <th>
                            <a href="#" style='text-decoration: none; color:black;'>{{quote.organization.organization_name}}</a>
                        </th>
                        <th>{% for item in quote.quoteitem_set.all %}{{ item.product.name }},{% endfor %}</th>
                        <th>
                            {% if quote.pdf_file %}
                                <button class='btn btn-success'>
                                    <a href="{{quote.pdf_file.url}}" style='text-decoration: none; color: white;'>دانلود</a>
                                </button>
                            {% else %}
                                -
                            {% endif %}
                        </th>
                        <th>
                            <a href="{% url 'quote:email_quote' quote.pk %}" style='text-decoration: none; color:black;'>ارسال ایمیل</a>
{#                            <a href="#" style='text-decoration: none; color:black;'>ارسال ایمیل</a>#}
                        </th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

                        <div class="clearfix"></div>
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                            {% endif %}
                            {% for page in paginator.page_range %}
                                {% if page == page_obj.number %}
                                    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="?page={{ page }}">{{ page }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                            {% endif %}
                        </ul>
{% endblock %}

templates/quote/pdf_quote.html
{% extends 'shared/_MainLayout.html' %}
{% load i18n %}
{% load humanize %}


{% block content %}
    <table class='table table-dark'>
        <thead>
                <tr>
                    <th>
                    <td colspan='7' class='text-center'>{{object.creator}}</td>

                </tr>
                <tr>
                <th>#</th>
                <th>{% trans "نام محصول" %}</th>
                <th>{% trans "تعداد خرید" %}</th>
                <th>{% trans "قیمت خام (تومان)" %}</th>
                <th>{% trans "قیمت اصلی (تومان)" %}</th>
                <th>{% trans "قیمت نهایی (تومان)" %}</th>
            </tr>
        </thead>

        <tbody>
            {% for quoteitem in object.quoteitem_set.all %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{quoteitem.product}}</td>
                    <td>{{quoteitem.number}}</td>
                    <td>{{quoteitem.price|intcomma}}</td>
                    <td>{{quoteitem.cost_with_tax|intcomma}}</td>
                    <td>{{quoteitem.final_price|intcomma}}</td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan='7' class='text-center'><span>{{object.sum_price|intcomma}}</span>{% trans "جمع خام هزینه ها" %} :</td>
            </tr>
            <tr>
                <td colspan='7' class='text-center'><span>{{object.sum_final_cost|intcomma}}</span>{% trans "جمع نهایی هزینه ها" %} :</td>
            </tr>
            <tr>
                <td colspan='7' class='text-center'><span>{{object.timestamp|date:"Y-m-d , H:i:s"}}</span>{% trans "ثبت شده در تاریخ" %} :</td>
            </tr>
        </tbody>
    </table>
{% endblock content %}