django_CRM_Project/urls.py
from django.contrib import admin
from django.urls import path,include
# load static file
from django.conf import settings
from django.conf.urls.static import static
from .views import home_page,header,footer
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from organization.views import OrganizationViewSetAPI

router = DefaultRouter()
router.register('organization', OrganizationViewSetAPI)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page,name="homepage"),
    path('header', header, name="header"),
    path('footer', footer, name="footer"),
    path('', include('user_accounts.urls')),
    path('', include('product.urls')),
    path('', include('organization.urls')),
    path('', include('quote.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),

]



# Static File Setting
if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # python manage.py collectstatic

    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organization/urls.py
from django.urls import path
from .views import Organization_Form,Organization_List,Organization_Detail, Organization_update

app_name = 'organization'
urlpatterns = [
    path('formorg',Organization_Form.as_view(),name='form'),
    path('listorg',Organization_List.as_view(),name='list'),
    path('detailorg/<int:pk>',Organization_Detail.as_view(),name='detail'),
    path('updateorg/<int:pk>',Organization_update.as_view(),name="Update"),
    ]

product/urls.py
from django.urls import path
from .views import ProductsList,CreatProductForm

app_name = 'product'

urlpatterns = [
    path('productform', CreatProductForm.as_view(),name='product_form'),
    path('products', ProductsList.as_view(),name='product_list'),

    ]

quote/urls.py
from django.urls import path
from .views import Quotes_Form, ListQuotes, DownloadQuote, send_quote_email, Follow_Up, ListFollow_Up

app_name = 'quote'
urlpatterns = [
    path('formquote', Quotes_Form.as_view(), name='form_quote'),
    path('listquote', ListQuotes.as_view(), name='list_quote'),
    path('download/<int:pk>/', DownloadQuote.as_view(), name='pdf_quote'),
    path('email/<int:pk>', send_quote_email, name='email_quote'),
    path('followup/<int:pk>/', Follow_Up.as_view(), name='follow_up'),
    path('listfollowup', ListFollow_Up.as_view(), name='list_follow_up'),

]

templates/shared/Footer.html
<footer id="footer"><!--Footer-->
    <div class="footer-Before">
        <div class="container">
            <div class="block-news">
                <div class="row">
                    <h3> عضویت در خبـرنامه ما  </h3>
                    <div class="searchform newslatter">
                        <input type="text" placeholder="آدرس ایمیـل شما ..."/>
                        <button type="submit" class="btn btn-default">
                            <i class="fa fa-arrow-circle-o-left"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <div class="address">
                        <img src="images/home/map.png" alt=""/>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="address">
                        <img src="images/home/map.png" alt=""/>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="companyinfo">
{#                        <h2><span>SHOP</span>CENTER</h2>#}
                        <h4>درباره ما :</h4>
                        <p>
                            {{ about_us }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{#    <div class="footer-widget">#}
{#        <div class="container">#}
{#            <div class="row">#}
{#                <div class="col-sm-3">#}
{#                    <div class="single-widget">#}
{#                        <h2>Service</h2>#}
{#                        <ul class="nav nav-pills nav-stacked">#}
{#                            <li><a href="#">Online Help</a></li>#}
{#                            <li><a href="#">Contact Us</a></li>#}
{#                            <li><a href="#">Order Status</a></li>#}
{#                            <li><a href="#">Change Location</a></li>#}
{#                            <li><a href="#">FAQ’s</a></li>#}
{#                        </ul>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-sm-3">#}
{#                    <div class="single-widget">#}
{#                        <h2>Quock Shop</h2>#}
{#                        <ul class="nav nav-pills nav-stacked">#}
{#                            <li><a href="#">T-Shirt</a></li>#}
{#                            <li><a href="#">Mens</a></li>#}
{#                            <li><a href="#">Womens</a></li>#}
{#                            <li><a href="#">Gift Cards</a></li>#}
{#                            <li><a href="#">Shoes</a></li>#}
{#                        </ul>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-sm-3">#}
{#                    <div class="single-widget">#}
{#                        <h2>Policies</h2>#}
{#                        <ul class="nav nav-pills nav-stacked">#}
{#                            <li><a href="#">Terms of Use</a></li>#}
{#                            <li><a href="#">Privecy Policy</a></li>#}
{#                            <li><a href="#">Refund Policy</a></li>#}
{#                            <li><a href="#">Billing System</a></li>#}
{#                            <li><a href="#">Ticket System</a></li>#}
{#                        </ul>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-sm-3">#}
{#                    <div class="single-widget">#}
{#                        <h2>About Shopper</h2>#}
{#                        <ul class="nav nav-pills nav-stacked">#}
{#                            <li><a href="#">Company Information</a></li>#}
{#                            <li><a href="#">Careers</a></li>#}
{#                            <li><a href="#">Store Location</a></li>#}
{#                            <li><a href="#">Affillate Program</a></li>#}
{#                            <li><a href="#">Copyright</a></li>#}
{#                        </ul>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}

    <div class="footer-bottom" style="direction: ltr !important;">
        <div class="container">
            <div class="row">
                <p class="pull-left">Copyright © 2018
                    <a target="_blank" href="http://www.1614GP.ir"><b>1614Group</b></a>. All rights reserved.
                </p>
            </div>
        </div>
    </div>

</footer><!--/Footer-->

templates/shared/Header.html
{% load static %}
<header id="header"><!--header-->
    <div class="header_top"><!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> 80 21 24 36 98+ </a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle"><!--header-middle-->
        <div class="container">
            <div class="row">
                <!-- <div class="col-sm-4 header-middle-menu">
                    <div class="shop-menu pull-left">
                        <ul class="nav navbar-nav">
                            <li><a href="checkout.html"><i class="fa fa-crosshairs"></i> پرداخت</a></li>
                        </ul>
                    </div>
                </div> -->

{#                <div class="col-sm-4" style="text-align: left;">#}
{#                    <div class="logo">#}
{#                        <a href="index.html"><img src="{% static 'images/home/logo.png' %}" alt="Logo"#}
{#                                                  style="text-align: center;"/></a>#}
{#                    </div>#}
{#                </div>#}

                <div class="col-sm-8 header-middle-menu">
                    <div class="shop-menu pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-user"></i> حساب کاربـری</a></li>
{#                            <li><a href="#"><i class="fa fa-star"></i> لیست علاقه مندی ها</a></li>#}
{#                            <li><a href="cart.html"><i class="fa fa-shopping-cart"></i> سبد خریـد</a></li>#}

                            {% if not request.user.is_authenticated %}
                                <li><a href="/login"><i class="fa fa-lock"></i> ورود</a></li>
                                <li><a href="/register"><i class="fa fa-lock"></i> ثبت نام</a></li>
                            {% else %}
                                <li><a href="/admin/logout"><i class="fa fa-lock"></i> خروج </a></li>
                            {% endif %}

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">

                {% include 'shared/search_products_input_component.html' %}

                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-right">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li><a href="/">خـانه</a></li>
{#                            <li><a href="/products">محصولات</a></li>#}
                            <li class="dropdown"><a href="/product">پنل محصولات<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    {% if  request.user.is_authenticated %}
                                        <li><a href="{% url 'product:product_form' %}">تعریف محصول</a></li>
                                        <li><a href="{% url 'product:product_list' %}">لیست محصولات</a></li>
                                    {% endif %}
                                </ul>
                            </li>
                            <li class="dropdown"><a href="#">پنل سازمانها<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    {% if  request.user.is_authenticated %}
                                        <li><a href="{% url 'organization:form' %}">تعریف سازمان</a></li>
                                        <li><a href="{% url 'organization:list' %}">سازمان های همکار</a></li>
                                        <li><a href="{% url 'quote:form_quote' %}">پیش فاکتور</a></li>
                                        <li><a href="{% url 'quote:list_quote' %}">لیست پیش فاکتور</a></li>
                                    {% else %}
                                        <li><a href="{% url 'organization:list' %}">سازمان های همکار</a></li>
                                    {% endif %}

                                </ul>
                            </li>
                            <li><a href="About.html">درباره مـا</a></li>
                            <li><a href="contact-us.html">تماس با مـا</a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

templates/shared/_FooterReferences.html
{% load static %}
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
<script src="{% static 'js/price-range.js' %}"></script>
<script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

templates/shared/_HeaderReferences.html
{% load static %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
<link href="{% static 'css/price-range.css' %}" rel="stylesheet">
<link href="{% static 'css/animate.css' %}" rel="stylesheet">
<link href="{% static 'css/main.css' %}" rel="stylesheet">
<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
<!--[if lt IE 9]>
    <script src="{% static 'js/html5shiv.js' %}"></script>
    <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->
<link rel="shortcut icon" href="{% static 'images/ico/favicon.ico' %}">
<link rel="apple-touch-icon-precomposed" sizes="144x144"
      href="{% static 'images/ico/apple-touch-icon-144-precomposed.png' %}">
<link rel="apple-touch-icon-precomposed" sizes="114x114"
      href="{% static 'images/ico/apple-touch-icon-114-precomposed.png' %}">
<link rel="apple-touch-icon-precomposed" sizes="72x72"
      href="{% static 'images/ico/apple-touch-icon-72-precomposed.png' %}">
<link rel="apple-touch-icon-precomposed" href="{% static 'images/ico/apple-touch-icon-57-precomposed.png' %}">

templates/shared/_MainLayout.html
{% load static %}
{% load render_partial %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>شرکت استیل البرز</title>
    {% include 'shared/_HeaderReferences.html' %}
    {% block header_ref %}{% endblock %}
</head>
<body>

{% render_partial 'header' %}

{% block content %}{% endblock %}
{% render_partial 'footer' %}
{% include 'shared/_FooterReferences.html' %}
{% block footer_ref %}{% endblock %}
{% block scripts %}{% endblock %}
</body>
</html>

templates/shared/search_products_input_component.html
<div class="col-sm-3">
    <div class="search_box pull-left">
        <form action="/products/search" method="get">
            <input type="text" placeholder="جستـجو" value="{{ request.GET.q }}" name="q"/>
        </form>
    </div>
</div>